### ISSUE TITLE
Allow NFT holders to bypass 2000 SGB check

### ISSUE THREAD

**Issue by stjet** [HelloMokuzai/AstralCredits#4]
Astral NFT badge holders should not need to hold 2000 SGB to use the faucet

**Comment by HelloMokuzai** [comment]
Consideration should be made to also include a cooldown period to ensure they can't be used to circumvent faucet security. As NFT badges by nature are generally low velocity.

This will still provide a net benefit to NFT badge holders by reducing the need hold funds indefinitely to make claims.

**Comment by HelloMokuzai** [comment]
Issue solved in PR #6
